config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :todo_lists do
    resources :todo_items
  end

  root "todo_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[ show edit update destroy ]

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1 or /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists or /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully created." }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: "Todo list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<div id="<%= dom_id todo_list %>">
  <div>
    <strong>Title:</strong>
    <p id="todo-title"><%= todo_list.title %></p>
  </div>

  <div>
    <strong>Description:</strong>
    <p id="todo-description"><%= todo_list.description %></p>
  </div>

</div>

app/views/todo_lists/edit.html.erb
<h1>Editing todo list</h1>

<%= render "form", todo_list: @todo_list %>

<br>

<div>
  <%= link_to "Show this todo list", @todo_list, id: "todo-show" %> |
  <%= link_to "Back to todo lists", todo_lists_path, id: "todo-back-to-list" %>
</div>

app/views/todo_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todo lists</h1>

<div id="todo_lists">
  <% @todo_lists.each do |todo_list| %>
    <%= render todo_list %>
    <p>
      <%= link_to "Show this todo list", todo_list, id: "todo-list-link" %>
    </p>
  <% end %>
</div>

<%= link_to "New todo list", new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New todo list</h1>

<%= render "form", todo_list: @todo_list %>

<br>

<div>
  <%= link_to "Back to todo lists", todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo_list %>

<div>
  <%= link_to "Edit this todo list", edit_todo_list_path(@todo_list), id: "todo-edit" %> |
  <%= link_to "Back to todo lists", todo_lists_path, id: "todo-back-to-list" %>

  <%= button_to "Destroy this todo list", @todo_list, method: :delete, id: "todo-destroy" %>
</div>